/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cainiao_jni_Worker */

#ifndef _Included_com_cainiao_jni_Worker
#define _Included_com_cainiao_jni_Worker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cainiao_jni_Worker
 * Method:    getTids
 * Signature: ([Ljava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_cainiao_jni_Worker_getTids
  (JNIEnv *, jclass, jobjectArray, jint);

/*
 * Class:     com_cainiao_jni_Worker
 * Method:    getDocids
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_cainiao_jni_Worker_getDocids
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     com_cainiao_jni_Worker
 * Method:    getDocVector
 * Signature: (I)[Lcom/cainiao/jni/DocVectorNode;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cainiao_jni_Worker_getDocVector
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_cainiao_jni_Worker
 * Method:    initEngine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cainiao_jni_Worker_initEngine
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
